#!/usr/bin/perl
use YAML;
use FlagDay;
use File::Basename;
use strict;
use feature 'switch';

my $config = YAML::LoadFile('config.yml')
	or die "Could not load config.yml\n";

my $dpkg = {};

print "Fetching dpkg package lists\n";
for my $host (@{$config->{hosts}}) {
	my $name = $host->{name};
	next unless $host->{dpkg};
	print "  $name\n";
	$dpkg->{$name} = join("\n", FlagDay::ssh($name, 'dpkg --get-selections'));
}

YAML::DumpFile("$ENV{FLAGDAY_INVENTORY}/dpkg.yml", $dpkg);
