#!/usr/bin/perl
use YAML;
use FlagDay;
use File::Basename;
use strict;
use feature 'switch';

my $config = YAML::LoadFile('config.yml')
	or die "Could not load config.yml\n";

my $filesystems = {};

my @hosts = map { $_->{name} } @{$config->{hosts}};

print "Fetching filesystems\n";
for my $name (@hosts) {
	print "  $name\n";
	my $fs = $filesystems->{$name} = [];
	my @fstab = FlagDay::ssh($name, 'cat /etc/fstab');
	for (@fstab) {
		s/#.*$//;
		next if $_ eq '';
		my ($device, $mountpoint, $fstype) = split(/\s+/);
		next if $fstype ~~ [qw/swap proc auto devpts tmpfs/];
		if ($device =~ /^UUID=(.*)$/) {
			my $uuid = $1;
			my ($real_device) = FlagDay::ssh($name, qq!realpath /dev/disk/by-uuid/$uuid!);
			if ($real_device) {
				$device = $real_device;
			}
		}
		push @{$fs}, {
			device => $device,
			mountpoint => $mountpoint,
			type => $fstype,
		}
	}
}

YAML::DumpFile("$ENV{FLAGDAY_INVENTORY}/filesystems.yml", $filesystems);
