#!/usr/bin/perl
use YAML;
use FlagDay;
use strict;

my $config = YAML::LoadFile('config.yml')
	or die "Could not load config.yml\n";

mkdir $ENV{FLAGDAY_FILES}
	unless -d $ENV{FLAGDAY_FILES};

print "Fetching files over SMB\n";
for my $host (@{$config->{hosts}}) {
	next unless exists $host->{smbfs};
	print "  $host->{name}\n";
	for my $path (@{$host->{smbfs}}) {
		print "    $path...\n";
		my @path = split('/', $path);
		my $safe_path = join('_', @path);
		my $share = shift @path;
		$path = join('/', @path);
		my $outfile = "$ENV{FLAGDAY_FILES}/$host->{name}-$safe_path.tar.gz";
		if (-e $outfile) {
			print "      Refusing to overwriting $outfile\n";
			next;
		}
		my $auth;
		if ($host->{smbauth}) {
			open AUTH, '>', 'smbauth';
			chmod 0600, *AUTH;
			print AUTH "username = $host->{smbauth}->{username}\n";
			print AUTH "password = $host->{smbauth}->{password}\n";
			print AUTH "domain = $host->{smbauth}->{domain}\n";
			close AUTH;
			$auth = '-A smbauth';
		}
		system qq!smbclient //$host->{name}/$share $auth -d0 -Tc - $path | gzip >$outfile!;
		if ($? >> 8 != 0) {
			die "Failed to back up //$host->{name}/share/$path\n";
		}
		unlink 'smbauth' if -e 'smbauth';
	}
}
