#!/usr/bin/perl
use YAML;
use strict;
use feature 'switch';

my $config = YAML::LoadFile('config.yml')
	or die "Could not load config.yml\n";

mkdir $ENV{FLAGDAY_GENERATED}
	unless -d $ENV{FLAGDAY_GENERATED};

my $passwd;
if (-e "$ENV{FLAGDAY_GENERATED}/accounts.yml") {
	$passwd = YAML::LoadFile("$ENV{FLAGDAY_GENERATED}/accounts.yml");
} else {
	$passwd = {};
}

print "Generating new passwords\n";
for my $account (@{$config->{accounts}}) {
	if (exists $passwd->{$account}) {
		print "  Password already exists for $account; skipping...\n";
		next;
	}
	my $len = $config->{options}->{'password-length'} || 12;
	my $password = qx!pwgen -ync $len!;
	chomp $password;
	$passwd->{$account} = $password;
}

YAML::DumpFile("$ENV{FLAGDAY_GENERATED}/accounts.yml", $passwd);
