#!/usr/bin/perl
use YAML;
use Cwd;
use strict;

my $config = YAML::LoadFile('config.yml')
	or die "Could not load config.yml\n";

$ENV{FLAGDAY_INVENTORY} = getcwd . '/inventory';

for my $module (@{$config->{'inventory-modules'}}) {
	system qq!inventory-modules/$module!;
	if ($? >> 8 != 0) {
		die "$module failed\n";
	}
}
